# Generated by Django 2.2.2 on 2020-12-19 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='complaints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propic', models.CharField(max_length=600)),
                ('name', models.CharField(max_length=400)),
                ('compname', models.CharField(max_length=400)),
                ('pic1', models.ImageField(null=True, upload_to='')),
                ('pic2', models.ImageField(null=True, upload_to='')),
                ('place', models.CharField(max_length=400)),
                ('city', models.CharField(max_length=400)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('desc', models.CharField(max_length=500, null=True)),
                ('upvote', models.IntegerField()),
            ],
        ),
    ]
