# Generated by Django 2.2.2 on 2020-12-19 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_complaints'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='status',
            field=models.CharField(choices=[('open', 'open'), ('no action taken', 'no action taken'), ('submitted to the newspaper', 'submitted to the newspaper'), ('resolved', 'resolved')], max_length=100, null=True),
        ),
    ]
