# Generated by Django 2.2.2 on 2020-12-19 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_complaints_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='propic',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='upvote',
            field=models.IntegerField(null=True),
        ),
    ]
