# Generated by Django 2.2.2 on 2020-12-19 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0004_auto_20201219_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='pic3',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
