# Generated by Django 2.2.2 on 2020-12-20 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0006_auto_20201220_0716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='cha',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='issues.chat'),
        ),
    ]
