# Generated by Django 2.2.2 on 2020-12-20 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0007_auto_20201220_0739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaints',
            name='cha',
        ),
    ]
