# Generated by Django 2.2.2 on 2020-12-20 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0008_remove_complaints_cha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='status',
            field=models.CharField(choices=[('open', 'open'), ('no action taken', 'no action taken'), ('submitted to the newspaper', 'submitted to the newspaper'), ('resolved', 'resolved')], default='open', max_length=100, null=True),
        ),
    ]
