# Generated by Django 2.2.2 on 2020-12-20 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0009_auto_20201220_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='pic1',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='pic2',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='pic3',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
