# Generated by Django 2.2.2 on 2020-12-20 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0010_auto_20201220_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='propic',
            field=models.CharField(default='', max_length=600),
        ),
    ]
