# Generated by Django 2.2.2 on 2020-12-20 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0012_auto_20201220_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='chats',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='issues.chat'),
        ),
    ]
