# Generated by Django 2.2.2 on 2020-12-20 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0016_remove_complaints_chats'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='cid',
            field=models.IntegerField(default=0),
        ),
    ]
