# Generated by Django 2.2.2 on 2020-12-20 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0017_chat_cid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='upvote',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
